//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NooseMod_LCPDFR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NooseMod_LCPDFR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminate all ~r~threats~w~ and watch for the hostages. Good luck..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_FIGHT_SUSPECTS {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_FIGHT_SUSPECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining terrorists are fleeing. Don&apos;t let them escape!.
        /// </summary>
        public static string CALLOUT_NOOSEMOD_FLEEING_TERRORISTS {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_FLEEING_TERRORISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorists are executing hostages! Hurry up!.
        /// </summary>
        public static string CALLOUT_NOOSEMOD_HOSTAGES_BEING_EXECUTED {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_HOSTAGES_BEING_EXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch, I&apos;m in position with the officers at {0}..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_PLAYER_IN_POS {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_PLAYER_IN_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOOSE is requesting police backup for fleeing terrorists at {0}..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_POLICE_BACKUP_REQUIRED {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_POLICE_BACKUP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the second team to arrive. Do not charge in to the target..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_STANDBY {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_STANDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available NOOSE units respond to the terrorist activity in {0}..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer is requesting NOOSE presence for a criminal in a gun spree in {0}..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_2 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS Message received, relaying orders: an officer is requesting NOOSE presence in {0}..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_3 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a possible terrorist activity in {0}, NOOSE presence is required..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_4 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Biker Gang has wrecked the peace in {0}, NOOSE presence is required..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_5 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS Message received, relaying orders: Assault and Battery confirmed at {0}, available NOOSE units, please respond..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_6 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilians are reporting criminals taking hostages. Police has been dispatched. Any available NOOSE units are required at {0} for assist..
        /// </summary>
        public static string CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_7 {
            get {
                return ResourceManager.GetString("CALLOUT_NOOSEMOD_TERRORIST_ACTIVITY_7", resourceCulture);
            }
        }
    }
}
